### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ivandrofly** [ivandrofly/subtitleedit#2]
## Add
- [ ] Add split view (COMPARE SUBTITLES FORM)
- [ ] Drag selection subtitle list view item
- [ ] Send pull request from directly from [XmlContentTranslator](https://github.com/SubtitleEdit/XmlContentTranslator) (github-api)
- [ ] Support of reading Lyrics3 from mp3 files (http://id3.org/Lyrics3v2)
- [ ] Allow sorting by clicking colum in main listview (SubtitleEdit listview).
- [ ] Auto update.
- [ ] Save support Ebu subtitle format.
- [ ] Start with a empty new paragraph (textbox focused) (PR sent).
## Fix
- [x] Remove all italic tags when CTRL+I is pressed:  <i><I>foobar</I></i>.
- [ ] https://github.com/ivandrofly/subtitleedit/issues/3
- [ ] Slow resize Main form.
- [ ] Separate Unitest from Solution file. (Add specific UnitTest fro LibSE)
- [ ] LibSE.cproj (remove <Target Name="BeforeCompile">) so others project can include LibSE.cproj
- [ ] https://github.com/SubtitleEdit/subtitleedit/issues/311 (https://github.com/ivandrofly/subtitleedit/tree/patch-310)

## Optimize
- [ ] Find should start looking for text at given index.
## REFACT
- [x] ~~Use HtmlUtil's **ToggleTag** and remove Main.cs'~~
  - [x] Remove all suffixed "**ToogleTag**" in Main.cs and start using HtmlUtil.ToggleTag.
- [ ] Move DecodeTimeCodeFrames/ThreeParts/Four/Two from SubtitleFormats.cs to TimeCode.cs
- [ ] Move method which uses string to (StringUtils)
- [ ] Move GetOptimalDisplayMilliSeconds from Utilities to TimeCode
- [ ] Escape regex string using Regex.Escape() (Utilities.cs)
- [ ] Merge FixCommonErrors: FixStartWithUppercaseLetterAfterPeriodInsideParagraph, FixStartWithUppercaseLetterAfterParagraph, FixStartWithUppercaseLetterAfterColon
- [ ] Move Logics from Helper.cs to its respective classes e.g: FixHyphenAdd
